package ir.synix.lockdown.rules;

import ir.synix.lockdown.rules.model.ActionPlan;
import ir.synix.lockdown.rules.model.Rule;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Reads {@link Rule} objects from a YAML {@code rules:} list or section map.
 * Shared by {@code rules.yml} and the auto-generated {@code commands/<Plugin>.yml} files.
 */
public final class RuleReader {

    private RuleReader() {
    }

    /** Read a list of rules from the given section's {@code rules} key. */
    public static List<Rule> readAll(ConfigurationSection parent, String pluginName) {
        List<Rule> out = new ArrayList<>();
        if (parent == null) return out;

        // Format 1: A List of Maps (like manual rules.yml or safely-merged command files)
        if (parent.isList("rules")) {
            List<?> raw = parent.getList("rules");
            if (raw != null) {
                for (Object o : raw) {
                    if (o instanceof Map<?, ?> m) {
                        Rule r = readOne(m, pluginName);
                        if (r != null) out.add(r);
                    }
                }
            }
        }
        // Format 2: A ConfigurationSection mapping (like fresh-scanned command files generated by buildFresh)
        else if (parent.isConfigurationSection("rules")) {
            ConfigurationSection rulesSec = parent.getConfigurationSection("rules");
            if (rulesSec != null) {
                for (String key : rulesSec.getKeys(false)) {
                    if (rulesSec.isConfigurationSection(key)) {
                        ConfigurationSection rSec = rulesSec.getConfigurationSection(key);
                        Rule r = readOne(sectionToMap(rSec), pluginName);
                        if (r != null) out.add(r);
                    } else if (rulesSec.get(key) instanceof Map<?, ?> m) {
                        Rule r = readOne(m, pluginName);
                        if (r != null) out.add(r);
                    }
                }
            }
        }
        return out;
    }

    @SuppressWarnings("unchecked")
    private static Rule readOne(Map<?, ?> m, String fallbackPlugin) {
        String id = str(m.get("id"));
        if (id == null || id.isBlank()) return null;
        String plugin = orDefault(str(m.get("plugin")), fallbackPlugin);

        Rule r = new Rule(id, plugin);
        r.setEnabled(bool(m.get("enabled"), false));

        // Patterns
        Object p = m.get("patterns");
        if (p instanceof List<?> pl) {
            List<String> pats = new ArrayList<>();
            for (Object o : pl) if (o != null) pats.add(o.toString());
            r.setPatterns(pats);
        } else if (p instanceof String ps) {
            r.setPatterns(List.of(ps));
        }
        r.setPermissionHint(str(m.get("permission")));

        r.setOnAuthorized(readPlan(asMap(m.get("on_authorized"))));
        r.setOnUnauthorized(readPlan(asMap(m.get("on_unauthorized"))));
        r.setOnFailure(readPlan(asMap(m.get("on_failure"))));
        return r;
    }

    private static Map<?, ?> asMap(Object o) {
        return o instanceof Map<?, ?> m ? m : null;
    }

    private static ActionPlan readPlan(Map<?, ?> m) {
        if (m == null) return ActionPlan.empty();
        return new ActionPlan(
                bool(m.get("log"), false),
                bool(m.get("notify"), false),
                bool(m.get("block"), false),
                bool(m.get("require_confirmation"), false),
                bool(m.get("freeze"), false));
    }

    /** Recursively converts a Bukkit ConfigurationSection to a standard Java Map */
    private static Map<String, Object> sectionToMap(ConfigurationSection sec) {
        Map<String, Object> map = new LinkedHashMap<>();
        for (String key : sec.getKeys(false)) {
            Object val = sec.get(key);
            if (val instanceof ConfigurationSection sub) {
                map.put(key, sectionToMap(sub));
            } else {
                map.put(key, val);
            }
        }
        return map;
    }

    private static String str(Object o) {
        return o == null ? null : o.toString();
    }

    private static String orDefault(String s, String def) {
        return (s == null || s.isBlank()) ? def : s;
    }

    private static boolean bool(Object o, boolean def) {
        if (o == null) return def;
        if (o instanceof Boolean b) return b;
        return Boolean.parseBoolean(o.toString().toLowerCase(Locale.ROOT));
    }

    public static List<Rule> fromConfig(FileConfiguration cfg, String pluginName) {
        return readAll(cfg, pluginName);
    }
}
