package ir.synix.lockdown.command;

import ir.synix.lockdown.LockDownPlugin;
import ir.synix.lockdown.config.ConfigManager;
import ir.synix.lockdown.config.Settings;
import ir.synix.lockdown.util.CommandMapAccess;

import org.bukkit.command.Command;
import org.bukkit.command.PluginCommand;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Logger;

/**
 * Scans registered server commands and maintains per-plugin generated command-rule configuration files.
 */
public final class CommandIndex {

    private final LockDownPlugin plugin;
    private final ConfigManager config;

    public CommandIndex(LockDownPlugin plugin, ConfigManager config) {
        this.plugin = plugin;
        this.config = config;
    }

    public record ScanResult(int commandCount, int fileCount, boolean forced) {}

    public ScanResult scan(boolean force, Map<String, Command> known) {
        Logger log = plugin.getLogger();
        Settings s = config.settings();

        Map<String, Map<String, Command>> byPlugin = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        if (known == null || known.isEmpty()) {
            log.warning("[LockDown] No commands discovered (command map unavailable).");
            return new ScanResult(0, 0, force);
        }

        Set<String> covered = new HashSet<>();
        for (Map.Entry<String, Command> entry : known.entrySet()) {
            Command cmd = entry.getValue();
            if (cmd == null) continue;

            String name = cmd.getName().toLowerCase(Locale.ROOT);
            if (covered.contains(name)) continue;

            covered.add(name);
            for (String alias : cmd.getAliases()) {
                covered.add(alias.toLowerCase(Locale.ROOT));
            }

            String owner = CommandMapAccess.ownerOf(cmd, log);
            if (owner == null || owner.isBlank()) owner = s.scan.defaultPluginFile;
            byPlugin.computeIfAbsent(owner, k -> new LinkedHashMap<>()).put(name, cmd);
        }

        ensureSelf(byPlugin);

        File dir = config.file("commands");
        if (!dir.exists() && !dir.mkdirs()) {
            log.warning("[LockDown] Could not create " + dir);
            return new ScanResult(0, 0, force);
        }

        int total = 0;
        for (Map.Entry<String, Map<String, Command>> e : byPlugin.entrySet()) {
            String owner = e.getKey();
            String fileBase = CommandMapAccess.slug(owner);
            File f = new File(dir, fileBase + ".yml");
            writePluginFile(f, owner, e.getValue(), force, s);
            total += e.getValue().size();
        }
        return new ScanResult(total, byPlugin.size(), force);
    }

    private void ensureSelf(Map<String, Map<String, Command>> byPlugin) {
        Map<String, Command> self = byPlugin.computeIfAbsent("LockDown", k -> new LinkedHashMap<>());
        PluginCommand ld = plugin.getCommand("lockdown");
        if (ld != null) self.putIfAbsent("lockdown", ld);
    }

    private void writePluginFile(File file, String owner, Map<String, Command> commands,
                                 boolean force, Settings s) {
        YamlConfiguration out = new YamlConfiguration();
        out.options().width(120);

        if (force || !file.exists() || !s.scan.safeMerge) {
            buildFresh(out, owner, commands, s);
        } else {
            mergeInto(YamlConfiguration.loadConfiguration(file), out, owner, commands, s);
        }

        try {
            out.save(file);
        } catch (IOException e) {
            plugin.getLogger().warning("[LockDown] Could not write " + file + ": " + e.getMessage());
        }
    }

    private void buildFresh(YamlConfiguration out, String owner, Map<String, Command> commands, Settings s) {
        out.set("plugin", owner);
        out.set("_comment", "Auto-generated by /lockdown scan. Flip 'enabled: true' to activate a rule.");

        ConfigurationSection rulesSec = out.createSection("rules");
        for (Command cmd : commands.values()) {
            String name = cmd.getName().toLowerCase(Locale.ROOT);
            String safeName = name.replace(".", "_");

            ConfigurationSection r = rulesSec.createSection(safeName);

            r.set("id", safeId(owner, safeName));
            r.set("enabled", false);

            List<String> patterns = new ArrayList<>();
            patterns.add(name);
            for (String alias : cmd.getAliases()) {
                String a = alias.toLowerCase(Locale.ROOT);
                if (!patterns.contains(a)) patterns.add(a);
            }
            r.set("patterns", patterns);

            if (cmd.getPermission() != null && !cmd.getPermission().isBlank()) {
                r.set("permission", cmd.getPermission());
            }

            Map<String, Object> auth = new LinkedHashMap<>();
            auth.put("log", true);
            auth.put("notify", true);
            auth.put("require_confirmation", true);
            r.set("on_authorized", auth);

            Map<String, Object> unauth = new LinkedHashMap<>();
            unauth.put("log", true);
            unauth.put("notify", true);
            unauth.put("block", true);
            unauth.put("freeze", true);
            r.set("on_unauthorized", unauth);
        }
    }

    private void mergeInto(YamlConfiguration existing, YamlConfiguration out,
                           String owner, Map<String, Command> commands, Settings s) {
        out.set("plugin", owner);
        out.set("_comment", existing.getString("_comment", "Auto-generated by /lockdown scan. Flip 'enabled: true' to activate."));

        ConfigurationSection oldRules = existing.getConfigurationSection("rules");
        ConfigurationSection newRules = out.createSection("rules");

        Set<String> coveredPatterns = new HashSet<>();

        if (oldRules != null) {
            for (String key : oldRules.getKeys(false)) {
                newRules.set(key, oldRules.get(key));
                List<String> pats = oldRules.getStringList(key + ".patterns");
                for (String p : pats) coveredPatterns.add(p.toLowerCase(Locale.ROOT));
            }
        }

        for (Command cmd : commands.values()) {
            String name = cmd.getName().toLowerCase(Locale.ROOT);
            String safeName = name.replace(".", "_");

            if (oldRules != null && oldRules.contains(safeName)) continue;
            if (coveredPatterns.contains(name)) continue;

            boolean aliasCovered = false;
            for (String a : cmd.getAliases()) {
                if (coveredPatterns.contains(a.toLowerCase(Locale.ROOT))) {
                    aliasCovered = true;
                    break;
                }
            }
            if (aliasCovered) continue;

            ConfigurationSection r = newRules.createSection(safeName);

            r.set("id", safeId(owner, safeName));
            r.set("enabled", false);

            List<String> patterns = new ArrayList<>();
            patterns.add(name);
            for (String alias : cmd.getAliases()) {
                String a = alias.toLowerCase(Locale.ROOT);
                if (!patterns.contains(a)) patterns.add(a);
            }
            r.set("patterns", patterns);

            if (cmd.getPermission() != null && !cmd.getPermission().isBlank()) {
                r.set("permission", cmd.getPermission());
            }

            Map<String, Object> auth = new LinkedHashMap<>();
            auth.put("log", true);
            auth.put("notify", true);
            auth.put("require_confirmation", true);
            r.set("on_authorized", auth);

            Map<String, Object> unauth = new LinkedHashMap<>();
            unauth.put("log", true);
            unauth.put("notify", true);
            unauth.put("block", true);
            unauth.put("freeze", true);
            r.set("on_unauthorized", unauth);
        }
    }

    private static String safeId(String plugin, String name) {
        String base = (name == null ? "rule" : name).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_]", "_");
        return plugin.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_]", "_") + "_" + base;
    }
}
